### PR TITLE
Updated to OpenShift 3.6

### PR DESCRIPTION
**Pull request by jr00n**
Support for OpenShift's Arbitrary User IDs by fixing the seluser
file and directory permissions and changing the WORKDIR
https://docs.openshift.org/latest/creating_images/guidelines.html

### CODE REVIEW

**Comment by mfvitale** [comment]
Any news about this? I have the same problem with OpenShift

**Comment by ddavison** [comment]
sorry it took so long to get to this.  

I don't use OpenShift anymore so i cannot guarantee the workability of these template changes.

i'm also curious about the `Dockerfile` additions?  what will these be used for?

**Comment by jr00n** [comment]
The changes in the Dockerfile needed to support openshift’s default to only Support Arbitrary User IDs

**Comment by devilmind** [comment]
Hi All,
I'm using openshift 3.9 and I have deployed the file following the blog http://ddavison.io/2016/02/01/openshift-templates-for-selenium.html

In the deployment logs of selenium-hub I see the following error:

`2018-10-09 08:49:04,990 WARN Included extra file "/etc/supervisor/conf.d/selenium-hub.conf" during parsing 2018-10-09 08:49:04,996 INFO supervisord started with pid 6 2018-10-09 08:49:05,999 INFO spawned: 'selenium-hub' with pid 9 supervisor: couldn't setuid to 1000: Can't drop privilege as nonroot user supervisor: child process was not spawned 2018-10-09 08:49:06,002 INFO success: selenium-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs) 2018-10-09 08:49:06,002 INFO exited: selenium-hub (exit status 127; not expected)`

I'm not able to connect to the Selenium Web Console and the selenium-node-chrome logs tells:

`08:55:31.322 WARN - error getting the parameters from the hub. The node may end up with wrong timeouts.Connect to selenium-hub:4444 [selenium-hub/172.30.129.107] failed: Connection refused (Connection refused) 2018-10-09 08:55:31.378:INFO::main: Logging initialized @1929ms to org.seleniumhq.jetty9.util.log.StdErrLog 2018-10-09 08:55:31.577:INFO:osjs.Server:main: jetty-9.4.5.v20170502 2018-10-09 08:55:31.608:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@245b4bdc{/,null,STARTING} has uncovered http methods for path: / 2018-10-09 08:55:31.612:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@245b4bdc{/,null,AVAILABLE} 2018-10-09 08:55:31.792:INFO:osjs.AbstractConnector:main: Started ServerConnector@293a5bf6{HTTP/1.1,[http/1.1]}{0.0.0.0:5555} 2018-10-09 08:55:31.792:INFO:osjs.Server:main: Started @2343ms`

Can someone help me please?
I'm stucked :(

**Pull request merged**
