### PR TITLE
Adding Chrome and Firefox debug templates

### LINKED ISSUE #7: Add Debug Templates
Currently there are node-chrome and node-firefox.

It'd be nice to have node-chrome-debug and node-firefox-debug.

### PR DESCRIPTION
**Pull request by jemacom**
This PR closes #7 
Add debug template to chrome. 

Since this PR is work in progress, I need feedback on it.  Then if every thing works well it'll be ready to merge.

### CODE REVIEW

**Comment by ddavison** [comment]
sweet, thanks! this LGTM 👍 

you have the WIP prefix - is this ready to merge, then?

**Comment by jemacom** [comment]
The chrome node join successfully the Selenium hub. But I can't VNC view the pod.
I create a route to the pod on port 5900. `http://selenium-node-chrome-debug-vnc-myproject.192.168.99.100.nip.io/`.

When I open that URL I got this on the logs:
screenshot from 2018-06-22 18-09-40

Which I trying to understand and fix.

### Enviroment: 
minishift v1.18.0+756b128

**Comment by ddavison** [comment]
perhaps when you figure this out then, you can document it in a `README.md` inside of the debug directories on how to connect to it. 

thanks!! 👍  🎉

**Comment by jemacom** [comment]
Accessing the chrome debug pod wasn't possible using openshift route on port 5900. The only thing that worked is by using port forwarding.
```
oc port-forward -p <POD_NAME> 5900:5900
```
And then access the pod
```
vncviewer 127.0.0.1:5900
```

**Comment by jemacom** [comment]
The Firefox template is ready as well !

**Comment by ddavison** [comment]
this is fantastic.. thanks very much!  this'll help a lot of people out.

**Pull request merged**
